@startuml Job

class Job {
    - {static} __job_count: int
    - __id: int
    - __title: str
    - __company: str
    - __salary: int | None
    - __description: str | None
    
    + {static} jobs_from_file(): list[Job]
    + __init__(title: str, company: str, salary: int | None = None, description: str | None = None, id: int | None = None)
    + set_salary(new_salary: int): void
    + update_description(new_description: str): void
    + save(): void
    + __str__(): str
}

note right of Job
  Represents a job listing
  Do not use commas in any text fields
  title, company, salary, description
end note

@enduml